- name: Check if Kibana package is installed
  ansible.builtin.command: rpm -q kibana  # noqa: command-instead-of-module
  register: kibana_pkg_check
  changed_when: false
  failed_when: false

- name: Check if Kibana service exists
  ansible.builtin.command: systemctl status kibana  # noqa: command-instead-of-module
  register: kibana_svc_check
  changed_when: false
  failed_when: false

- name: DEBUG | Kibana availability summary
  ansible.builtin.debug:
    msg:
      - "Package installed : {{ kibana_pkg_check.rc == 0 }}"
      - "Service exists    : {{ kibana_svc_check.rc == 0 }}"
